### ISSUE TITLE
Initial selection of "Stages:" Checkboxes not saved when creating new conventions

### ISSUE THREAD

**Issue by blackfurball** [eurofurence/Stage-Squirrel#21]
Steps to reproduce:
1. Login with Admin privileges
2. Navigate to: Managing -> Conventions
3. Use "Add convention" button
4. Fill in form with random data and -> check any of the available stages <-
5. Click "Create"
6. Click Edit button at the just created convention

Observed behavior: No check-boxes at the stages are checked
Expected behavior: Previously checked check-boxes should be checked. 

Re checking them in the edit dialog and accepting the changes with "Edit" saves them properly.

**Comment by kandril** [comment]
[Relevant line in commit](https://github.com/eurofurence/Stage-Squirrel/commit/f60daa95f3d03471de8297290dc655b7fe216f6b#diff-2433476a2ed630b7a22680523e547de4R50) ;)

**Comment by kandril** [comment]
Already pulled above mentioned commit on the live-server

**Comment by blackfurball** [comment]
Yep, is fixed! Thx!
