### ISSUE TITLE
Survey disappears from "My surveys" after editing

### ISSUE THREAD

**Issue by blackfurball** [eurofurence/Stage-Squirrel#23]
When editing an already existing survey, it disappears after saving changes.

Steps to reproduce:
Using the installation from https://github.com/eurofurence/Stage-Squirrel/issues/22 (cant avoid the bug from this issue right now)

1. User with Event Manager privileges: Navigate to "Create Survey" tab
2. Fill in plausible data in form
3. Click Create Event (and get dump from issue 22)
4. Hit back button in your browser and navigate to "My Surveys" tab
5. Click on the "show Survey" link in the line coressponding to your newly created test event
6. Hit "update Event" button (You actually don't have to update anything in the form to trigger the update)
7. Confirm the Message box with Ok
8. Navigate back to "My Surveys" 

Observed behavior: Edited event is missing from the list
Expected behavior: The edited event should still be listed here. 

Using a user with admin privileges and looming at the "Manage Events" tab, where all events should be listed regardless of ownershow, the faulty events are now listed like:

`Title Event-Manager Event Day Survey Mine Mgr Rider`
`null UNKNOWN_CREATOR - edit Survey create Rider`

logs are again stored on prod machine in ~/bugfixing/

**Comment by blackfurball** [comment]
This issue could of course be related to #22. I've decided to log this in case the error survives #22  :)

**Comment by kandril** [comment]
Due to an error in the selection of the correct dropdown option for the convention date, sometimes the empty string was sent as a new value, which causes the underlying `INSERT`-Query for `event_details` to brake.
Should be fixed, now

**Comment by kandril** [comment]
Already pulled above mentioned commit on the live-server

**Comment by blackfurball** [comment]
Retested and confirmed issue is fixed. Thanks again :]
